### ISSUE TITLE
Change greenkeeper to renovate

### ISSUE THREAD

**Issue by neighborhood999** [hermeslin/guardian-of-env#38]
greenkeeper 不會直接幫你更新 lockfile，renovate 會幫你處理一起更新，可以考慮換過去。先到 [installations](https://github.com/settings/installations) 把 greenkeeper 設定過的 repo 移除掉，再到 [renovate](https://github.com/apps/renovate) 這邊安裝這個 app 設定。

類似像這樣：https://github.com/neighborhood999/next-fiveN1/pull/57

不過它改動了版號，少了 `^`，看了一下其他有在用的人好像都改成這樣，需要再研究一下

**Comment by hermeslin** [comment]
改成固定版號嗎？這看起來不錯，我再來試著移到 renovate

**Comment by neighborhood999** [comment]
對，它就是變成固定版號，只是不知道這樣會有沒有什麼問題就是 XD

**Comment by hermeslin** [comment]
不知道這樣做是不是為了要解決 npm install 跟 yarn intall 的 lock file 不一樣的問題嗎？

**Comment by neighborhood999** [comment]
不太確定哈哈，但感覺這麼做有它的用意

**Comment by neighborhood999** [comment]
我找到這個專門 for lib 用的設定：`config:js-lib`

ref: https://docs.renovatebot.com/presets-config/

**Comment by hermeslin** [comment]
#43 
加入 renovate
